name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: POST Endpoint
      id: post-endpoint
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: POST Endpoint
        setup-command: ''
        command: mvn -Dtest=FlightApiApplicationTests#testFlightEndpointWithPOST test
        timeout: 10
        max-score: 4
    - name: GETList Endpoint
      id: getlist-endpoint
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: GETList Endpoint
        setup-command: ''
        command: mvn -Dtest=FlightApiApplicationTests#testFlightEndpointWithGETList
          test
        timeout: 10
        max-score: 4
    - name: GETListAndOriginFilter Endpoint
      id: getlistandoriginfilter-endpoint
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: GETListAndOriginFilter Endpoint
        setup-command: ''
        command: mvn -Dtest=FlightApiApplicationTests#testFlightEndpointWithGETListAndOriginFilter
          test
        timeout: 10
        max-score: 4
    - name: GETListAndDestinationOrder Endpoint
      id: getlistanddestinationorder-endpoint
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: GETListAndDestinationOrder Endpoint
        setup-command: ''
        command: mvn -Dtest=FlightApiApplicationTests#testFlightEndpointWithGETListAndDestinationOrder
          test
        timeout: 10
        max-score: 4
    - name: GETById Endpoint
      id: getbyid-endpoint
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: GETById Endpoint
        setup-command: ''
        command: mvn -Dtest=FlightApiApplicationTests#testFlightEndpointWithGETById
          test
        timeout: 10
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        POST-ENDPOINT_RESULTS: "${{steps.post-endpoint.outputs.result}}"
        GETLIST-ENDPOINT_RESULTS: "${{steps.getlist-endpoint.outputs.result}}"
        GETLISTANDORIGINFILTER-ENDPOINT_RESULTS: "${{steps.getlistandoriginfilter-endpoint.outputs.result}}"
        GETLISTANDDESTINATIONORDER-ENDPOINT_RESULTS: "${{steps.getlistanddestinationorder-endpoint.outputs.result}}"
        GETBYID-ENDPOINT_RESULTS: "${{steps.getbyid-endpoint.outputs.result}}"
      with:
        runners: post-endpoint,getlist-endpoint,getlistandoriginfilter-endpoint,getlistanddestinationorder-endpoint,getbyid-endpoint
