name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Maven test
      id: maven-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Maven test
        setup-command: ''
        command: mvn clean test
        timeout: 10
        max-score: 20
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        MAVEN-TEST_RESULTS: "${{steps.maven-test.outputs.result}}"
      with:
        runners: maven-test
